import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import Image from 'next/image';
import fw from '../public/framework.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import p1 from "../public/Project1.mp4";
import p2 from "../public/project2.mp4";
import p3 from "../public/project3.mp4";
import p4 from "../public/project4.mp4";
import gaming from "../public/Gaming-bro.png";
import { useState } from 'react';



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [read1, setRead1] = useState(false);
  const [read2, setRead2] = useState(false);
  const [read3, setRead3] = useState(false);
  const [read4, setRead4] = useState(false);

  const handleReadMore = (projectNumber) => {
    switch (projectNumber) {
      case 1:
        setRead1(!read1);
        break;
      case 2:
        setRead2(!read2);
        break;
      case 3:
        setRead3(!read3);
        break;
      case 4:
        setRead4(!read4);
        break;
      default:
        break;
    }
  };

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>ElKhattab Yasser Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className='bg-white w-full flex items-center justify-center flex-col px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
      <section className='min-h-screen w-full'>
        <nav className='py-10 mb-12 flex justify-between w-full'>
          <h1 className='text-2xl font-Burtons dark:text-white'>YasserYr</h1>
          <ul className='flex flex-row items-center'>
            <li><BsFillMoonStarsFill onClick={()=>setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white'/></li>
          </ul>
        </nav>
        <div className='text-center p-10'>
          <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Elkhattab Yasser</h2>
          <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Junior Developer</h3>
          <p className='text-xl py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-300'>Je suis un développeur junior avec une passion pour la programmation et le développement full stack
          </p>
        </div>
        <div className=' flex items-center justify-center'>
          <div className='relative sm:w-80 w-64 mx-auto bg-gradient-to-b from-teal-500 rounded-full sm:h-80 h-64 overflow-hidden mb-28 mt-20 md:h-96 md:w-96'> 
            <Image src={gaming} layout='fill' objectFit='cover' alt='avatar'/>
          </div>
        </div>
      </section>

      <section className=' w-full'>
        <div className=' w-full'>
          <h3 className='text-3xl font-bold py-1 mt-10 dark:text-white'>Skills</h3>
          <p className='text-xl py-2 leading-8 text-slate-700 dark:text-gray-300'>
            Depuis le début de mes études en développement Full Stack, j'ai acquis de nombreuses compétences, en voici quelques-unes :
          </p>
        </div>
        <div className="lg:flex gap-10">
          <div className='text-center w-[98%]  shadow-lg dark:shadow-slate-800 p-10 rounded-xl my-10 lg:w-1/3'>
            <Image src={fw} width={120} height={120} className='m-auto' alt='framework logo'/>
            <h3 className='text-xl font-semibold pt-8 pb-2 dark:text-white'>Les frameworks</h3>
            <h4 className='py-4 text-teal-600'>Les frameworks que j'utilise :</h4>
            <p className='text-gray-800 py-1 dark:text-gray-300'>MERN Stack</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>Laravel</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>Tailwind CSS</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>Bootstrap</p>
          </div>

          <div className='text-center w-[98%] shadow-lg dark:shadow-slate-800 p-10 rounded-xl my-10 lg:w-1/3'>
            <Image src={code} width={120} height={120} className='m-auto' alt='programmation logo'/>
            <h3 className='text-xl font-semibold pt-8 pb-2 dark:text-white'>Les langages de programmation</h3>
            <h4 className='py-4 text-teal-600'> Les langages de programmation que j'utilise :</h4>
            <p className='text-gray-800 py-1 dark:text-gray-300'>JavaScript</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>PHP</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>Python</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>C</p>
          </div>

          <div className='text-center w-[98%] shadow-lg dark:shadow-slate-800 p-10 rounded-xl my-10 lg:w-1/3'>
            <Image src={consulting} width={120} height={120} className='m-auto' alt='database logo'/>
            <h3 className='text-xl font-semibold pt-8 pb-2 dark:text-white'>Databases</h3>
            <h4 className='py-4 text-teal-600'>Les Databases que j'utilise :</h4>
            <p className='text-gray-800 py-1 dark:text-gray-300'>MongoDB</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>PL SQL</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>My SQL</p>
          </div>
        </div>
      </section>
      <section className=' w-full'>
        <div className=' w-full'>
          <h3 className='text-3xl font-bold py-1 dark:text-white'>Portofolio</h3>
          <p className='text-xl py-2 leading-8 text-slate-700 dark:text-gray-300'>
          Embarkant sur mon parcours en tant que développeur junior en Full Stack,
          je m'investis activement dans l'apprentissage continu et la réalisation de projets pour renforcer mes compétences.
          Alors que je continue de progresser dans <span className=' text-teal-500'>le développement MERN</span> et d'explorer des frameworks tels que <span className=' text-teal-500'>Laravel</span>, 
          ma priorité reste l'apprentissage constant et son application pratique.
          Mon portfolio présente certains de mes projets qui illustrent ma croissance continue
          et ma détermination à élargir mes connaissances et mon expérience en développement web. 
          Je suis enthousiaste à l'idée de perfectionner mes compétences et de contribuer à des solutions innovantes dans le domaine.
          </p>
        </div>
        <div className='flex flex-col gap-10 sm:py-10 py-0 mt-28'>
          <div className=' w-full grid xl:grid-cols-2 gap-7'>
            <div className="flex rounded-lg  w-full">
              <div className="rounded-lg shadow-lg bg-white w-full">
                <video height="240" controls className="w-full rounded-t-lg">
                  <source src={p1} type="video/mp4"/>
                </video>
                <div className="p-6">
                  <h5 className="text-teal-500 text-3xl font-bold mb-2">Paradise Store</h5>
                  <p className="text-gray-700 sm:text-xl text-base mb-4">
                  Expérience dans le développement d'une application de magasin MERN réactive offrant une authentification sécurisée
                  avec JWT et bcrypt pour la connexion et l'inscription des utilisateurs. <span className={`${read1? 'block' : 'hidden'}`}>Exploration d'un catalogue de produits 
                  diversifié avec un filtrage facile basé sur les types, tandis que des routes protégées garantissent une expérience
                  personnalisée et sécurisée. Les utilisateurs connectés peuvent gérer 
                  facilement un panier d'achat personnalisé, permettant des paiements en ligne pour un processus de paiement fluide. </span>
                  </p>
                  <button onClick={() => handleReadMore(1)} className='border border-teal-500 text-teal-500 text-xl py-2 px-4 rounded-3xl hover:scale-105 duration-500 ease-linear transition-all'>{read1? 'Read Less' : 'Read More'}</button>
                </div>
              </div>
            </div>

            <div className="flex rounded-lg  w-full">
              <div className="rounded-lg shadow-lg bg-white w-full">
                <video height="240" controls className="w-full rounded-t-lg">
                  <source src={p2} type="video/mp4"/>
                </video>
                <div className="p-6">
                  <h5 className="text-teal-500 text-3xl font-bold mb-2">BookingSpace</h5>
                  <p className="text-gray-700 sm:text-xl text-base mb-4">
                  Présentation d'une plateforme de réservation dynamique basée sur MERN, similaire à des plateformes telles qu'Airbnb.
                  <span className={`${read2? 'block' : 'hidden'}`}>Cette application complète offre aux utilisateurs la possibilité d'explorer une gamme diversifiée d'annonces immobilières,
                  soumises par divers utilisateurs, qu'ils soient connectés ou non. Les utilisateurs connectés bénéficient
                  de l'avantage supplémentaire de contribuer à la plateforme en ajoutant ou modifiant leurs propres annonces immobilières.
                  Grâce à une authentification sécurisée utilisant JWT et bcrypt, la plateforme assure une gestion de compte protégée.
                  Les utilisateurs peuvent parcourir, réserver et gérer facilement des logements, favorisant une expérience de réservation
                  fluide et interactive.</span>
                  </p>
                  <button onClick={() => handleReadMore(2)} className='border border-teal-500 text-teal-500 text-xl py-2 px-4 rounded-3xl hover:scale-105 duration-500 ease-linear transition-all'>{read2? 'Read Less' : 'Read More'}</button>
                </div>
              </div>
            </div>

            <div className="flex rounded-lg  w-full">
              <div className="rounded-lg shadow-lg bg-white w-full">
                <video height="240" controls className="w-full rounded-t-lg">
                  <source src={p3} type="video/mp4"/>
                </video>
                <div className="p-6">
                  <h5 className="text-teal-500 text-3xl font-bold mb-2">Samsung Store</h5>
                  <p className="text-gray-700 sm:text-xl text-base mb-4">
                  Expérience dans la création d'un site web réactif, mettant en œuvre React et Tailwind CSS pour assurer une expérience utilisateur
                  moderne et élégante. <span className={`${read3? 'block' : 'hidden'}`}>Le site offre une navigation fluide et une présentation attrayante des produits,
                  adaptée à divers dispositifs. Découvrez une plateforme centrée sur l'utilisateur, 
                  alliant la puissance de React et le style de Tailwind pour une expérience de shopping en ligne immersive et visuellement 
                  attrayante.</span>
                  </p>
                  <button onClick={() => handleReadMore(3)} className='border border-teal-500 text-teal-500 text-xl py-2 px-4 rounded-3xl hover:scale-105 duration-500 ease-linear transition-all'>{read3? 'Read Less' : 'Read More'}</button>
                </div>
              </div>
            </div>

            <div className="flex rounded-lg  w-full">
              <div className="rounded-lg shadow-lg bg-white w-full">
                <video height="240" controls className="w-full rounded-t-lg">
                  <source src={p4} type="video/mp4"/>
                </video>
                <div className="p-6">
                  <h5 className="text-teal-500 text-3xl font-bold mb-2">Brightness</h5>
                  <p className="text-gray-700 sm:text-xl text-base mb-4">
                  Brightness est une plateforme web intuitive développée avec la pile technologique MERN,
                  conçue pour simplifier les tâches quotidiennes des éducateurs. <span className={`${read4? 'block' : 'hidden'}`}>
                  Avec des comptes d'enseignants pré-créés, le système propose une interface conviviale où les enseignants peuvent gérer
                  facilement leurs classes, accéder aux listes d'élèves et saisir les notes des examens.
                  De plus, les enseignants peuvent suivre la progression des étudiants, favorisant une expérience d'enseignement
                  efficace et rationalisée. </span> 
                  </p>
                  <button onClick={() => handleReadMore(4)} className='border border-teal-500 text-teal-500 text-xl py-2 px-4 rounded-3xl hover:scale-105 duration-500 ease-linear transition-all'>{read4? 'Read Less' : 'Read More'}</button>
                </div>
              </div>
            </div>

          </div>
        </div>
      </section>
    </main>
    </div>
  )
}
