import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import Image from 'next/image';
import fw from '../public/framework.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import p1 from "../public/Project1.mp4";
import p2 from "../public/Project2.mp4";
import p3 from "../public/Project3.mp4";
import p4 from "../public/Project4.mp4";
import gaming from "../public/Gaming-bro.png";
import { useState } from 'react';



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>ElKhattab Yasser Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
      <section className='min-h-screen'>
        <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-2xl font-Burtons dark:text-white'>YasserYr</h1>
          <ul className='flex flex-row items-center'>
            <li><BsFillMoonStarsFill onClick={()=>setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white'/></li>
          </ul>
        </nav>
        <div className='text-center p-10'>
          <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Elkhattab Yasser</h2>
          <h3 className='text-2xl py-2 md:text-3xl dark:text-white'>Junior Developer</h3>
          <p className='text-xl py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-gray-300'>Je suis un développeur junior avec une passion pour la programmation et le développement full stack
          </p>
        </div>
        <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 m2-30 overflow-hidden mt-20 md:h-96 md:w-96'> 
          <Image src={gaming} layout='fill' objectFit='cover'/>
        </div>
      </section>

      <section>
        <div>
          <h3 className='text-3xl font-bold py-1 mt-10 dark:text-white'>Skills</h3>
          <p className='text-xl py-2 leading-8 text-slate-700 dark:text-gray-300'>
            Depuis le début de mes études en développement Full Stack, j'ai acquis de nombreuses compétences, en voici quelques-unes :
          </p>
        </div>
        <div className="lg:flex gap-10">
          <div className='text-center shadow-lg dark:shadow-slate-800 p-10 rounded-xl my-10 w-1/3'>
            <Image src={fw} width={120} height={120} className='m-auto'/>
            <h3 className='text-xl font-semibold pt-8 pb-2 dark:text-white'>Les frameworks</h3>
            <h4 className='py-4 text-teal-600'>Les frameworks que j'utilise :</h4>
            <p className='text-gray-800 py-1 dark:text-gray-300'>MERN Stack</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>Laravel</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>Tailwind CSS</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>Bootstrap</p>
          </div>

          <div className='text-center shadow-lg dark:shadow-slate-800 p-10 rounded-xl my-10 w-1/3'>
            <Image src={code} width={120} height={120} className='m-auto'/>
            <h3 className='text-xl font-semibold pt-8 pb-2 dark:text-white'>Les langages de programmation</h3>
            <h4 className='py-4 text-teal-600'> Les langages de programmation que j'utilise :</h4>
            <p className='text-gray-800 py-1 dark:text-gray-300'>JavaScript</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>PHP</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>Python</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>C</p>
          </div>

          <div className='text-center shadow-lg dark:shadow-slate-800 p-10 rounded-xl my-10 w-1/3'>
            <Image src={consulting} width={120} height={120} className='m-auto'/>
            <h3 className='text-xl font-semibold pt-8 pb-2 dark:text-white'>Databases</h3>
            <h4 className='py-4 text-teal-600'>Les Databases que j'utilise :</h4>
            <p className='text-gray-800 py-1 dark:text-gray-300'>MongoDB</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>PL SQL</p>
            <p className='text-gray-800 py-1 dark:text-gray-300'>My SQL</p>
          </div>
        </div>
      </section>
      <section>
        <div>
          <h3 className='text-3xl font-bold py-1 dark:text-white'>Portofolio</h3>
          <p className='text-xl py-2 leading-8 text-slate-700 dark:text-gray-300'>
          Embarkant sur mon parcours en tant que développeur junior en Full Stack,
          je m'investis activement dans l'apprentissage continu et la réalisation de projets pour renforcer mes compétences.
          Alors que je continue de progresser dans <span className=' text-teal-500'>le développement MERN</span> et d'explorer des frameworks tels que <span className=' text-teal-500'>Laravel</span>, 
          ma priorité reste l'apprentissage constant et son application pratique.
          Mon portfolio présente certains de mes projets qui illustrent ma croissance continue
          et ma détermination à élargir mes connaissances et mon expérience en développement web. 
          Je suis enthousiaste à l'idée de perfectionner mes compétences et de contribuer à des solutions innovantes dans le domaine.
          </p>
        </div>
        <div className='flex flex-col gap-10 py-10 mt-28'>
          <div className='basis-1/3 flex-1 flex'>
            <video className='rounded-lg object-cover' width={600} height={600} layout='responsive' controls >
              <source src={p1} type="video/mp4" />
            </video>
            <div className=' flex flex-col justify-start ml-8 gap-8'>
              <h1 className=' text-4xl font-bold text-teal-500'>Paradise Store</h1>
              <p className=' text-lg text-slate-700 dark:text-white'>Expérience dans le développement d'une application de magasin MERN réactive offrant une authentification sécurisée avec JWT et bcrypt pour la connexion et l'inscription des utilisateurs. Exploration d'un catalogue de produits diversifié avec un filtrage facile basé sur les types, tandis que des routes protégées garantissent une expérience personnalisée et sécurisée. Les utilisateurs connectés peuvent gérer facilement un panier d'achat personnalisé, permettant des paiements en ligne pour un processus de paiement fluide. </p>
            </div>
          </div>

          <div className='basis-1/3 flex-1 flex mt-20'>
            <div className=' flex flex-col justify-start mr-8 gap-8'>
              <h1 className=' text-4xl font-bold text-teal-500'>BookingSpace</h1>
              <p className=' text-lg text-slate-700 dark:text-white'>Présentation d'une plateforme de réservation dynamique basée sur MERN, similaire à des plateformes telles qu'Airbnb. Cette application complète offre aux utilisateurs la possibilité d'explorer une gamme diversifiée d'annonces immobilières, soumises par divers utilisateurs, qu'ils soient connectés ou non. Les utilisateurs connectés bénéficient de l'avantage supplémentaire de contribuer à la plateforme en ajoutant ou modifiant leurs propres annonces immobilières. Grâce à une authentification sécurisée utilisant JWT et bcrypt, la plateforme assure une gestion de compte protégée. Les utilisateurs peuvent parcourir, réserver et gérer facilement des logements, favorisant une expérience de réservation fluide et interactive.</p>
            </div>
            <video className='rounded-lg object-cover' width={600} height={600} layout='responsive' controls>
              <source src={p2} type="video/mp4" />
            </video>
          </div>

          <div className='basis-1/3 flex-1 flex mt-20'>
            <video className='rounded-lg object-cover' width={600} height={600} layout='responsive' controls >
              <source src={p3} type="video/mp4" />
            </video>
            <div className=' flex flex-col justify-start ml-8 gap-8'>
              <h1 className=' text-4xl font-bold text-teal-500'>Samsung Store</h1>
              <p className=' text-lg text-slate-700 dark:text-white'>Expérience dans la création d'un site web réactif, mettant en œuvre React et Tailwind CSS pour assurer une expérience utilisateur moderne et élégante. Le site offre une navigation fluide et une présentation attrayante des produits, adaptée à divers dispositifs. Découvrez une plateforme centrée sur l'utilisateur, alliant la puissance de React et le style de Tailwind pour une expérience de shopping en ligne immersive et visuellement attrayante.</p>
            </div>
          </div>

                    <div className='basis-1/3 flex-1 flex mt-20'>
            <div className=' flex flex-col justify-start mr-8 gap-8'>
              <h1 className=' text-4xl font-bold text-teal-500'>BookingSpace</h1>
              <p className=' text-lg text-slate-700 dark:text-white'>Présentation d'une plateforme de réservation dynamique basée sur MERN, similaire à des plateformes telles qu'Airbnb. Cette application complète offre aux utilisateurs la possibilité d'explorer une gamme diversifiée d'annonces immobilières, soumises par divers utilisateurs, qu'ils soient connectés ou non. Les utilisateurs connectés bénéficient de l'avantage supplémentaire de contribuer à la plateforme en ajoutant ou modifiant leurs propres annonces immobilières. Grâce à une authentification sécurisée utilisant JWT et bcrypt, la plateforme assure une gestion de compte protégée. Les utilisateurs peuvent parcourir, réserver et gérer facilement des logements, favorisant une expérience de réservation fluide et interactive.</p>
            </div>
            <video className='rounded-lg object-center' width={600} height={600} layout='responsive' controls>
              <source src={p4} type="video/mp4" />
            </video>
          </div>

        </div>
      </section>
    </main>
    </div>
  )
}
